CREATE TABLE products (id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(128) NOT NULL, price_cents BIGINT NOT NULL);
CREATE TABLE cart_items (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity BIGINT NOT NULL, UNIQUE KEY uq_cart (user_id, product_id), FOREIGN KEY (product_id) REFERENCES products(id));
