server.address=127.0.0.1
server.port=${PORT:8080}
spring.datasource.url=${X_MOCK_MYSQL_URL}
spring.datasource.username=mock
spring.datasource.password=mock-local
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.sql.init.mode=never
spring.flyway.enabled=false
spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto=none
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=5s
